const commonActionType = {
  TOGGLE_SNACK_BAR: "TOGGLE_SNACK_BAR",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  SET_SONGS_LIST: "SET_SONGS_LIST",
  SET_PLAYLIST_LIST: "SET_PLAYLIST_LIST",
  SET_SEARCH_SONGS_LIST: "SET_SEARCH_SONGS_LIST",
};

export default commonActionType;
